const restaurants = [
{id:'little-french',name:'Little French',area:'Westbury Park',cuisine:'French',price:'£££',score:4.8,tags:['Date night','Independent','Wine'],image:'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=1000&q=80',blurb:'Neighbourhood French cooking, excellent wine and a dangerously easy excuse to order dessert.',deal:'Demo deal · Midweek set menu · Tue–Thu',bookable:true},
{id:'pasta-ripiena',name:'Pasta Ripiena',area:'City Centre',cuisine:'Italian',price:'££',score:4.7,tags:['Pasta','Cosy','Independent'],image:'https://images.unsplash.com/photo-1473093295043-cdd812d0e601?auto=format&fit=crop&w=1000&q=80',blurb:'Tiny, lively and entirely committed to filled pasta. A strong contender for carb-based happiness.',deal:null,bookable:true},
{id:'squeezed',name:'Squeezed',area:'Wapping Wharf',cuisine:'Burgers',price:'££',score:4.6,tags:['Casual','Burgers','Harbourside'],image:'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=1000&q=80',blurb:'Messy burgers, brilliant chips and absolutely no expectation that you retain your dignity while eating.',deal:'Demo deal · Free fries with a double burger · Mondays',bookable:false},
{id:'seven-lucky-gods',name:'Seven Lucky Gods',area:'Wapping Wharf',cuisine:'Japanese',price:'££',score:4.5,tags:['Small plates','Cocktails','Groups'],image:'https://images.unsplash.com/photo-1553621042-f6e147245754?auto=format&fit=crop&w=1000&q=80',blurb:'Japanese-inspired small plates and cocktails made for ordering far too much “for the table”.',deal:null,bookable:true},
{id:'root',name:'Root',area:'Wapping Wharf',cuisine:'Modern British',price:'£££',score:4.7,tags:['Veg-forward','Seasonal','Small plates'],image:'https://images.unsplash.com/photo-1541544741938-0af808871cc0?auto=format&fit=crop&w=1000&q=80',blurb:'Vegetables get main-character treatment, without making the meat eaters feel like they have been punished.',deal:'Demo deal · Friday lunch tasting menu',bookable:true},
{id:'bokman',name:'Bokman',area:'Stokes Croft',cuisine:'Korean',price:'££',score:4.8,tags:['Korean','Sharing','Hidden gem'],image:'https://images.unsplash.com/photo-1498654896293-37aacf113fd9?auto=format&fit=crop&w=1000&q=80',blurb:'Bold Korean cooking and the sort of menu that makes choosing only one thing feel personally offensive.',deal:null,bookable:true},
{id:'bravas',name:'Bravas',area:'Clifton',cuisine:'Spanish',price:'££',score:4.6,tags:['Tapas','Date night','Clifton'],image:'https://images.unsplash.com/photo-1533777857889-4be7c70b33f7?auto=format&fit=crop&w=1000&q=80',blurb:'Bustling tapas bar energy, good sherry and plates that disappear before anyone remembers to photograph them.',deal:'Demo deal · Weekday lunch offer',bookable:true},
{id:'molto-buono',name:'Molto Buono',area:'Park Street',cuisine:'Italian',price:'££',score:4.4,tags:['Pizza','Pasta','Casual'],image:'https://images.unsplash.com/photo-1579751626657-72bc17010498?auto=format&fit=crop&w=1000&q=80',blurb:'Big comfort-food energy: pizza, pasta and the eternal question of whether ordering both is excessive.',deal:'Demo deal · Student pizza night · Wednesdays',bookable:true}
];
const defaultState={saved:['little-french','bokman'],visited:{'pasta-ripiena':{rating:5,note:'Would absolutely go back. Ravioli was ridiculous.'},squeezed:{rating:4,note:'Great burger. Needed approximately seventeen napkins.'},bravas:{rating:4,note:'Perfect for sharing and pretending I will not order another plate.'}}};
let state=load();let page='discover';let cuisine='All';let query='';
function load(){try{return Object.assign({},defaultState,JSON.parse(localStorage.getItem('bitebook-v1')||'{}'))}catch{return defaultState}}
function save(){localStorage.setItem('bitebook-v1',JSON.stringify(state))}
function points(){return Object.keys(state.visited).length*100+Object.values(state.visited).reduce((n,v)=>n+v.rating*10,0)}
function setPage(next){page=next;document.querySelectorAll('[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===page));render()}
document.querySelectorAll('[data-page]').forEach(b=>b.addEventListener('click',()=>setPage(b.dataset.page)));
document.getElementById('searchInput').addEventListener('input',e=>{query=e.target.value.toLowerCase();if(page!=='discover')setPage('discover');else render()});
function card(r){const v=state.visited[r.id];return `<article class="restaurant"><div class="restaurant-image" onclick="openRestaurant('${r.id}')"><img src="${r.image}" alt=""><span class="chip price">${r.price}</span>${r.deal?'<span class="chip deal">✦ Deal</span>':''}</div><div class="restaurant-body"><div class="restaurant-title"><div><h3>${r.name}</h3><div class="meta">⌖ ${r.area} · ${r.cuisine}</div></div><button class="save ${state.saved.includes(r.id)?'saved':''}" onclick="toggleSave('${r.id}')">${state.saved.includes(r.id)?'♥':'♡'}</button></div><p class="blurb">${r.blurb}</p><div class="tags">${r.tags.map(t=>`<span class="tag">${t}</span>`).join('')}</div><div class="card-foot"><span class="score">★ ${r.score}</span>${v?`<span class="visited">✓ In your BiteBook · ${v.rating}/5</span>`:''}<button class="view" onclick="openRestaurant('${r.id}')">View</button></div></div></article>`}
function title(k,t,c){return `<div class="title"><span class="eyebrow">${k}</span><h1>${t}</h1><p>${c}</p></div>`}
function render(){document.getElementById('topPoints').textContent=`${points()} pts`;const root=document.getElementById('app');if(page==='discover')root.innerHTML=discover();if(page==='bitebook')root.innerHTML=bitebook();if(page==='groups')root.innerHTML=groups();if(page==='deals')root.innerHTML=deals();if(page==='owners')root.innerHTML=owners();}
function discover(){const cs=['All',...new Set(restaurants.map(r=>r.cuisine))];const list=restaurants.filter(r=>`${r.name} ${r.area} ${r.cuisine} ${r.tags.join(' ')}`.toLowerCase().includes(query)&&(cuisine==='All'||r.cuisine===cuisine));const visited=Object.keys(state.visited).length;return `<div class="page"><section class="hero"><div><span class="eyebrow">✦ Bristol beta</span><h1>Your city. Your BiteBook.</h1><p>Find somewhere brilliant, tick it off, rate it, and quietly become unbearable about how many Bristol restaurants you've tried.</p><div class="actions"><button class="primary" onclick="document.getElementById('explore').scrollIntoView()">Find my next bite</button><button class="secondary" onclick="setPage('groups')">Invite friends</button></div></div><div class="hero-score"><span>Your BiteBook score</span><strong>${points()}</strong><small>${visited} places visited · Bristol rank #38</small><div class="progress"><i style="width:${Math.min(100,visited*12)}%"></i></div></div></section><section class="stats"><div class="stat"><span>Places tried</span><b>${visited}</b><small>Keep eating. Heroically.</small></div><div class="stat"><span>Want to try</span><b>${state.saved.length}</b><small>Your edible hit list</small></div><div class="stat"><span>Group position</span><b>#2</b><small>Nick is annoyingly ahead</small></div><div class="stat"><span>Badges</span><b>3</b><small>2 more almost unlocked</small></div></section><section id="explore"><div class="section-head"><div><span class="eyebrow">Explore</span><h2>Popular around Bristol</h2></div><div class="filters">${cs.map(c=>`<button onclick="setCuisine('${c.replaceAll("'","\\'")}')" class="${cuisine===c?'active':''}">${c}</button>`).join('')}</div></div><div class="restaurant-grid">${list.map(card).join('')}</div>${!list.length?'<div class="empty">No bites found. Bristol has failed you. Try another search.</div>':''}</section></div>`}
function setCuisine(c){cuisine=c;render()}
function bitebook(){const tried=restaurants.filter(r=>state.visited[r.id]);const wish=restaurants.filter(r=>state.saved.includes(r.id)&&!state.visited[r.id]);return `<div class="page">${title('Your collection','My BiteBook',"Every restaurant you've conquered, plus the ones currently living rent-free in your head.")}<div class="section-head"><div><span class="eyebrow">Stamped</span><h2>Places you've tried</h2></div></div><div class="restaurant-grid">${tried.map(card).join('')}</div><div class="section-head spaced"><div><span class="eyebrow">Wishlist</span><h2>Next on the hit list</h2></div></div><div class="restaurant-grid">${wish.map(card).join('')||'<div class="empty">Your wishlist is suspiciously empty.</div>'}</div></div>`}
function groups(){const p=points();const leaders=[['Nick',p+180,7,'N'],['Annie',p,6,'A'],['Hush',p-130,5,'H'],['Zay',p-240,4,'Z']];return `<div class="page">${title('Eat competitively','The Dinner Club',"Because apparently simply enjoying a meal wasn't enough; we needed a leaderboard.")}<div class="group-layout"><section class="leaderboard"><div class="leader-head"><b>🏆 August leaderboard</b><small style="display:block;color:#91847c">Resets in 19 days</small></div>${leaders.map((l,i)=>`<div class="leader ${l[0]==='Annie'?'me':''}"><span class="rank">${i+1}</span><div class="avatar">${l[3]}</div><div><b>${l[0]}</b><small>${l[2]} new restaurants this month</small></div><b>${l[1]} pts</b><span class="crown">${i===0?'👑':''}</span></div>`).join('')}</section><section class="challenge"><span class="eyebrow">🔥 Live challenge</span><h2>Passport: Wapping Wharf</h2><p>Visit four different restaurants in Wapping Wharf before the end of August.</p><b>2 / 4</b><div class="progress"><i style="width:50%"></i></div><p><b>Reward:</b> +300 pts & “Cargo Crawler” badge</p></section></div><div class="section-head spaced"><div><span class="eyebrow">Badges</span><h2>Bragging rights</h2></div></div><div class="badges">${[['🍝','Carb Loading','Try 5 Italian restaurants'],['🌶️','Bit Spicy','Try 5 spicy-food spots'],['🗺️','Bristol Explorer','Visit 8 different areas'],['🥂','Fancy Pants','Try 5 £££ restaurants']].map(x=>`<div class="badge"><span class="emoji">${x[0]}</span><b>${x[1]}</b><small>${x[2]}</small></div>`).join('')}</div></div>`}
function deals(){const list=restaurants.filter(r=>r.deal);return `<div class="page">${title('Member perks','BiteBook Deals','Offers from participating restaurants. Useful for discovering somewhere new; dangerous for your ability to cook at home.')}<div class="restaurant-grid">${list.map(card).join('')}</div><div class="note"><b>Prototype note:</b> these are clearly marked demo offers. Real restaurants should create and control their own offers before public launch.</div></div>`}
function owners(){return `<div class="page">${title('Restaurant partners','Put your restaurant in their BiteBook','A first-look at the restaurant side: claim your profile, add offers, see engagement and eventually manage bookings.')}<section class="owner-hero"><div><span class="eyebrow">▣ Free during Bristol beta</span><h2>Own or manage a restaurant?</h2><p>Claim your listing and keep your details, deals and booking options up to date. Paid plans can come later; right now the goal is making BiteBook genuinely useful to Bristol independents.</p><button class="primary" onclick="alert('Restaurant onboarding form is next on the build list.')">Claim your restaurant</button></div><div class="dash"><div class="dash-top"><span>This month</span><b>Little French</b></div><div class="dash-stats"><div><strong>1,284</strong><span>profile views</span></div><div><strong>214</strong><span>saves</span></div><div><strong>48</strong><span>booking taps</span></div></div><div class="chart">${[32,46,40,66,58,80,92].map(h=>`<i style="height:${h}%"></i>`).join('')}</div></div></section><div class="features"><div class="feature"><span class="ico">▣</span><b>Own your profile</b><p>Update description, photos, cuisine, opening info and booking links.</p></div><div class="feature"><span class="ico">✦</span><b>Publish deals</b><p>Give BiteBook users a reason to try you on quieter days.</p></div><div class="feature"><span class="ico">🏆</span><b>Join challenges</b><p>Opt into city and neighbourhood challenges that drive discovery.</p></div><div class="feature"><span class="ico">♟</span><b>Understand interest</b><p>See saves, profile views and engagement without needing to become a data scientist.</p></div></div><div class="note"><b>Backend-ready:</b> the included <code>supabase-schema.sql</code> gives us a starting database structure for accounts, restaurants, visits, wishlists, groups, deals and booking requests.</div></div>`}
function toggleSave(id){state.saved=state.saved.includes(id)?state.saved.filter(x=>x!==id):[...state.saved,id];save();render()}
function openRestaurant(id){const r=restaurants.find(x=>x.id===id);const v=state.visited[id];document.getElementById('modalRoot').innerHTML=`<div class="modal-bg" onclick="if(event.target===this)closeModal()"><section class="modal"><button class="close" onclick="closeModal()">✕</button><img src="${r.image}" alt=""><div class="modal-content"><span class="eyebrow">⌖ ${r.area} · ${r.cuisine}</span><h2>${r.name}</h2><p>${r.blurb}</p>${r.deal?`<div class="deal-box"><b>✦ BiteBook offer:</b> ${r.deal}</div>`:''}<div class="rating"><div><b>${v?'Your rating':'Been here?'}</b><small style="display:block;color:#84776e">${v?'Tap a star to change it.':'Rate it to add it to your BiteBook.'}</small></div><div class="stars">${[1,2,3,4,5].map(n=>`<button class="${n<=(v?.rating||0)?'on':''}" onclick="rate('${id}',${n})">★</button>`).join('')}</div></div>${v?.note?`<p><i>“${v.note}”</i></p>`:''}<div class="modal-actions">${r.bookable?'<button class="primary" onclick="alert(\'Booking requests are planned for v0.2.\')">Request a table</button>':'<span style="color:#8d8077;font-size:12px">Walk-in / external booking</span>'}</div></div></section></div>`}
function closeModal(){document.getElementById('modalRoot').innerHTML=''}
function rate(id,rating){state.visited[id]={rating,note:state.visited[id]?.note||''};save();openRestaurant(id);document.getElementById('topPoints').textContent=`${points()} pts`}
render();
